### ISSUE TITLE
Worklogs should use markdown

### ISSUE THREAD

**Issue by micaminoff** [micaminoff/micaminoff.github.io#3]
Erik almost has markdown in his worklog, but you still need spaces after the hyphens, and double linebreaks. [Check here](https://raw.githubusercontent.com/micaminoff/micaminoff.github.io/master/Documentation/Worklog-Michael.md) for reference.

Raphael, something strange is going on in your worklog. Tidy it up :D

**Comment by Raphnix** [comment]
errm - what strange?

**Comment by micaminoff** [comment]
Well, your worklog starts with <<<<<<< HEAD

You can compare our worklogs here. [Michael](https://github.com/micaminoff/micaminoff.github.io/blob/master/Documentation/Worklog-Michael.md) --- [Raphael](https://github.com/micaminoff/micaminoff.github.io/blob/master/Documentation/Worklog-Raphael.md).

You should use

```
* List item
                       //This makes the items lists
* List item 2

```
instead of

```
# List item
                       //This makes the items headers
# List item 2
```

Also remember to put a space after the special character \# and \*

Finally for stuff to show up on separate rows you need a blank line between the two lines
