### ISSUE TITLE
Make enemies slide into the screen

### ISSUE THREAD

**Issue by micaminoff** [micaminoff/micaminoff.github.io#32]
Right now the enemies just plop up on the screen. It would look way better if they spawned a bit further away and slid onto the background.

**Comment by micaminoff** [comment]
Assigned Erik so he can try his hand at editing some of the JS.

**Comment by eriksand** [comment]
Nice! :) Good thing you notified me of the assignment, because I didn't get any notifications about that. Strange, but whatever.

Spontaneous reaction: Is it going to be full of errors if I try to draw anything outside the canvas? Then it might not be so simple :)
