### ISSUE TITLE
Add projectile speed

### ISSUE THREAD

**Issue by micaminoff** [micaminoff/micaminoff.github.io#62]
Add a projectile speed to weapon attributes and animate the projectile.

This allows another aspect of modification when it comes to weapons - do I want a stronger weapon with slower travel time or do I want a weaker weapon that hits immediately?

Instead of immediately logging the clicked mouse location we can animate a projectile and add a timeout to the logging function and compare the location with the enemies array when the projectile has traveled. Maybe we could add a random component that slightly offsets projectile trajectory? Accuracy could be another weapon attribute that's worth considering.

@Raphnix @eriksand @lindami Do these sound like features we want? I feel like it could add strategic depth to the game as well as provide some additional programmatic challenge.

**Comment by eriksand** [comment]
Trebuchets! Slow and awesome :) Sounds like a great idea!
